extends: '@textshq/eslint-config/base.yml'
parserOptions:
  project: ./tsconfig.json
rules:
  "@typescript-eslint/no-unused-vars":
    - error
    -
      argsIgnorePattern: "^_"
      varsIgnorePattern: "^_"
      caughtErrorsIgnorePattern: "^_"
