name = "texts-sentry-proxy"
main = "src/index.ts"
compatibility_date = "2024-01-29"

# modify the following to match your environment
[vars]
ALLOWED_DSN = ""
SENTRY_INGEST_DOMAIN = "sentry.texts.com"
CLICKHOUSE_HOST = ""
CLICKHOUSE_USER = ""
CLICKHOUSE_PASSWORD = ""
